In [1]:
import pandas as pd
df = pd.read_csv("advertising/advertising.csv")
df = df.iloc[:,1:len(df)]
df.head()

TV  radio  newspaper  sales
0  230.1   37.8       69.2   22.1
1   44.5   39.3       45.1   10.4
2   17.2   45.9       69.3    9.3
3  151.5   41.3       58.5   18.5
4  180.8   10.8       58.4   12.9

In [2]:
X = df.drop("sales", axis = 1)
X.head()

TV  radio  newspaper
0  230.1   37.8       69.2
1   44.5   39.3       45.1
2   17.2   45.9       69.3
3  151.5   41.3       58.5
4  180.8   10.8       58.4

In [3]:
y = df[["sales"]]
y.head()

sales
0   22.1
1   10.4
2    9.3
3   18.5
4   12.9

In [7]:
import statsmodels.api as sm

In [8]:
lm = sm.OLS(y, X)

In [9]:
model = lm.fit()

In [10]:
model.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                                 OLS Regression Results                                
=======================================================================================
Dep. Variable:                  sales   R-squared (uncentered):                   0.982
Model:                            OLS   Adj. R-squared (uncentered):              0.982
Method:                 Least Squares   F-statistic:                              3566.
Date:                Fri, 01 May 2020   Prob (F-statistic):                   2.43e-171
Time:                        15:23:34   Log-Likelihood:                         -423.54
No. Observations:                 200   AIC:                                      853.1
Df Residuals:                     197   BIC:                                      863.0
Df Model:                           3                                                  
Covariance Type:            nonrobust                                                  
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
TV             0.0538      0.001     40.507      0.000       0.051       0.056
radio          0.2222      0.009     23.595      0.000       0.204       0.241
newspaper      0.0168      0.007      2.517      0.013       0.004       0.030
==============================================================================
Omnibus:                        5.982   Durbin-Watson:                   2.038
Prob(Omnibus):                  0.050   Jarque-Bera (JB):                7.039
Skew:                          -0.232   Prob(JB):                       0.0296
Kurtosis:                       3.794   Cond. No.                         12.6
==============================================================================

Warnings:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
"""

In [20]:
##scikit learn ile model kurmak

In [28]:
from sklearn.linear_model import LinearRegression
lm = LinearRegression()

In [29]:
model = lm.fit(X,y)

In [30]:
model.intercept_

array([2.93888937])

In [31]:
model.coef_

array([[ 0.04576465,  0.18853002, -0.00103749]])

Sales = 2.94 + TV * 0.04  +  radio * 0.19 - newspaper * 0.001

30 birim TV, 10 birim radio, 40 birim newspaper

In [32]:
 2.94 + 30 * 0.04  +  10 * 0.19 - 40 * 0.001

5.999999999999999

In [33]:
yeni_veri = [[30],[10],[40]]

In [34]:
import pandas as pd
yeni_veri = pd.DataFrame(yeni_veri).T
yeni_veri

0   1   2
0  30  10  40

In [35]:
model.predict(yeni_veri)

array([[6.15562918]])

In [36]:
yeni_veri = [[100],[120],[400]]
import pandas as pd
yeni_veri = pd.DataFrame(yeni_veri).T
yeni_veri

0    1    2
0  100  120  400

In [37]:
model.predict(yeni_veri)

array([[29.72395873]])

In [39]:
from sklearn.metrics import mean_squared_error

In [40]:
model.predict(X)[0:10]

array([[20.52397441],
       [12.33785482],
       [12.30767078],
       [17.59782951],
       [13.18867186],
       [12.47834763],
       [11.72975995],
       [12.12295317],
       [ 3.72734086],
       [12.55084872]])

In [44]:
MSE = mean_squared_error(y, model.predict(X))
MSE

2.784126314510936

In [45]:
import numpy as np
RMSE= np.sqrt(MSE)
RMSE

1.6685701407225697

In [46]:
##model tuning(model doğrulama)

In [47]:
X.head()

TV  radio  newspaper
0  230.1   37.8       69.2
1   44.5   39.3       45.1
2   17.2   45.9       69.3
3  151.5   41.3       58.5
4  180.8   10.8       58.4

In [48]:
y.head()

sales
0   22.1
1   10.4
2    9.3
3   18.5
4   12.9

In [49]:
#sınama seti

In [50]:
from sklearn.model_selection import train_test_split

In [72]:
X_train, X_test, y_train, y_test = train_test_split(X,y, test_size = 0.20, random_state=1)

In [59]:
X_train.head()

TV  radio  newspaper
16    67.8   36.6      114.0
51   100.4    9.6        3.6
97   184.9   21.0       22.0
164  117.2   14.7        5.4
71   109.8   14.3       31.7

In [60]:
y_train.head()

sales
16    12.5
51    10.7
97    15.5
164   11.9
71    12.4

In [61]:
X_test.head()

TV  radio  newspaper
135  48.3   47.0        8.5
127  80.2    0.0        9.2
191  75.5   10.8        6.0
66   31.5   24.6        2.2
119  19.4   16.0       22.3

In [62]:
y_test.head()

sales
135   11.6
127    8.8
191    9.9
66     9.5
119    6.6

In [73]:
from sklearn.linear_model import LinearRegression
lm = LinearRegression()
model = lm.fit(X_train, y_train)

In [74]:
#train hatası
np.sqrt(mean_squared_error(y_train, model.predict(X_train)))

1.7369025901470923

In [75]:
#test hatası
np.sqrt(mean_squared_error(y_test, model.predict(X_test)))

1.4113417558581578

In [76]:
#k-katlı cv

In [77]:
from sklearn.model_selection import cross_val_score

In [82]:
cross_val_score(model, X_train, y_train, cv=10, scoring="neg_mean_squared_error")

array([-1.62375953, -3.81875608, -3.43828142, -2.27748673, -7.25325414,
       -1.88303708, -2.80517715, -3.68594486, -1.12810834, -3.96330989])

In [83]:
#cv mse
np.mean(-cross_val_score(model, X_train, y_train, cv=10, scoring="neg_mean_squared_error"))

3.187711520944358

In [84]:
#cv rmse
np.sqrt(np.mean(-cross_val_score(model, X_train, y_train, cv=10, scoring="neg_mean_squared_error")))

1.7854163438661466